services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: secdb
    ports:
      - 5432:5432
    volumes:
      - psqldata:/var/lib/postgresql/data

volumes:
  psqldata:
