services:
  lq:
    image: liquibase/liquibase:4.29
    volumes:
      - ./src/main/resources/db:/liquibase/db
      - ./src/main/resources/liquibase.docker.properties:/liquibase/liquibase.docker.properties
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${POSTGRES_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
